### ISSUE TITLE
Problems running

### ISSUE THREAD

**Issue by qucchia** [micahlt/modchat#25]
**Describe the bug**
Thanks, -Archon-, I managed to clone the repo and start it, with the command `MCBANNED=none npm start`. On port 3001 the website appears as normal, but things start to go wrong when I try signing in. After entering my username, the loading animation started but never stopped. I looked at the terminal and saw some errors (see screenshot below). There seems to be a problem with SV... have you any idea what it could be?

**Expected behavior**
I'd expect it to behave as in the online app, supplying a code to be commented on my profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/45072410/99871002-8a1c3700-2bd7-11eb-8f21-d206d0bf3814.png)

**Additional context**
I'm trying to get this running to see if I can help contribute to Modchat :)

**Comment by micahlt** [comment]
@qucchia Hello there!  The issue you're experiencing is related to [environment variables](https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html).  Modchat uses these for several things, mostly related to API requests.  The error is that you don't have a ScratchVerifier API key set up, which you can do [here](https://scratchverifier.ddns.net/site/dashboard/).  Here's a list of the environment variables that should be set in order for Modchat to work properly: 

`MCBANNED`: this is the ban list and should be a list of usernames separated by spaces
`SVID`: this is your ScratchVerifier App ID
`SVSECRET`: this is your ScratchVerifier App Secret

Please test this out and let me know if the issue is resolved!

**Comment by qucchia** [comment]
Thanks Archon, it worked!
